apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
      matchLabels:
        name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
      - name: {{ .Release.Name }}
        image: namanarora/kubesnap:{{ .Values.image.tag }}
        volumeMounts:
          - name: git-secrets
            mountPath: /etc/secrets
            readOnly: true
          - name: config-volume
            mountPath: /etc/configs
            readOnly: true
          - name: ansible-config-volume
            mountPath: /etc/ansible
            readOnly: true
          - name: repo-data
            mountPath: /repo
        resources:
          requests:
            memory: {{ .Values.requests.memory | quote }}
            cpu: {{ .Values.requests.cpu | quote }}
          limits:
            memory: {{ .Values.limits.memory | quote }}
            cpu: {{ .Values.limits.cpu | quote }}
      volumes:
      - name: git-secrets
        secret:
          secretName: git-secrets
      - name: repo-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-vol-claim
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-config
      - name: ansible-config-volume
        configMap:
          name: {{ .Release.Name }}-ansible-config
