apiVersion: v1
kind: Secret
metadata:
  name: git-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  repo-url: {{ .Values.repo.url | quote | b64enc }}
  repo-branch: {{ .Values.repo.branch | quote | b64enc }}