apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-snap
  namespace: kube-snap
spec:
  replicas: 1
  selector:
      matchLabels:
        name: kube-snap
  template:
    metadata:
      labels:
        name: kube-snap
    spec:
      serviceAccountName: kube-snap-sa
      containers:
      - name: kube-snap
        image: namanarora/kube-snap:latest
        volumeMounts:
          - name: git-secrets
            mountPath: /etc/secrets
            readOnly: true
          - name: config-volume
            mountPath: /etc/configs
            readOnly: true
          - name: repo-data
            mountPath: /repo
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
      volumes:
      - name: git-secrets
        secret:
          secretName: git-secrets
      - name: repo-data
        persistentVolumeClaim:
          claimName: kube-snap-vol-claim
      - name: config-volume
        configMap:
          name: kube-snap-config
